---
- hosts: localhost

  vars_files:
    - vars/main.yml

  tasks:

    - name: Get list of apps installed with cask via `brew cask list`.
      command: brew cask list
      register: _homebrew_cask_list
      changed_when: false

    - name: Install apps via `brew cask`.
      command: >
        brew cask install {{ item }} --appdir={{ homebrew.cask.app_dir }}
      with_items: homebrew.cask.apps
      when: "'{{ item }}' not in _homebrew_cask_list.stdout"

    # - name: Register Alfred with homebrew_cask 
    #   command: brew cask alfred link

    - name: Install packages with homebrew
      homebrew: name={{item}} state=present
      with_items: homebrew.packages

    - name: Install packages with homebrew
      homebrew: name={{item}} state=linked
      with_items: homebrew.packages

    # - name: Install pip packages
    #   pip: name={{item}}
    #   with_items: pip.packages

    - name: Install custom SublimeText Themes
      git: >
        repo={{item.repo}} 
        dest="/Users/{{user}}/Library/Application Support/Sublime Text 2/Packages/Theme - {{item.name}}"
        accept_hostkey=yes
      with_items: sublime_text.themes
      ignore_errors: yes
        

    - name: Generate custom ~/.zshrc file
      template: >
        src=templates/zshrc.j2
        dest=/Users/{{user}}/.zshrc
        owner={{user}}
        mode=0644

    - name: Check if custom .zsh-theme exists
      stat: path=files/{{oh_my_zsh.theme.name}}.zsh-theme
      register: custom_theme

    - name: Copy custom them to oh-my-zsh dir
      copy: src=files/{{oh_my_zsh.theme.name}}.zsh-theme dest=/Users/{{user}}/{{oh_my_zsh.dir}}/themes/
      when: ! custom_theme.stat.exists

    - name: Register Git user
      command: >
        git config --global user.name "{{git.global.user_name}}"

    - name: Register Git email
      command: >
        git config --global user.email "{{git.global.user_email}}"

    # - name: Start services at login
    #   file: src=/usr/local/opt//homebrew.mxcl..plist path=~/Library/LaunchAgents/homebrew.mxcl..plist state=link force=yes
    #   with_items: launchctl.services

    # - name: Setup launch agents for services
    #   command: launchctl load /Library/LaunchAgents/homebrew.mxcl..plist
    #   with_items: launchctl.services








